import { Head } from "../components/layout/Head";
import Image from "next/image";
import { Layout } from "../components/layout/Layout";
import { HeroSection } from "../components/layout/sections/HeroSection";
import { AboutSection } from "../components/layout/sections/AboutSection";
import { ServicesSection } from "../components/layout/sections/ServicesSection";
import { PortfolioSection } from "../components/layout/sections/PortfolioSection";
import { PartnersSection } from "../components/layout/sections/PartnersSection";
import { ContactSection } from "../components/layout/sections/ContactSection";

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <HeroSection />
      <AboutSection />
      <ServicesSection />
      <PortfolioSection />
      <PartnersSection />
      <ContactSection />
    </Layout>
  );
}
